[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
onchain_academy = "64XGGSc32TUX7rxge5u4Qsv55RQN5ybSwS4B1eksWTxy"

[programs.devnet]
onchain_academy = "64XGGSc32TUX7rxge5u4Qsv55RQN5ybSwS4B1eksWTxy"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "../wallets/signer.json"

[test.validator]
bind_address = "127.0.0.1"

[[test.genesis]]
address = "CoREENxT6tW1HoK8ypY1SxRMZTcVPm7R94rH4PZNhX7d"
program = "tests/fixtures/mpl_core.so"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
